### PR TITLE
fix: MethodDeclarationStructure should write an asterisk isGenerator = true

### LINKED ISSUE #1501: MethodDeclarationStructure with isGenerator: true does not serialize with the asterisk
**Describe the bug**

Version: 21.0.1

**To Reproduce**

```ts
import { Project } from "ts-morph";

const project = new Project();
const sourceFile = project.createSourceFile("test.ts", {
  statements: [
    {
      kind: StructureKind.Function,
      name: "foo",
      isGenerator: true,
      returnType: "IterableIterator<number>",
      statements: ["yield 1;", "yield 2;"],
    },
    {
      kind: StructureKind.Class,
      name: "MyClass",
      methods: [
        {
          kind: StructureKind.Method,
          name: "foo",
          isGenerator: true,
          returnType: "IterableIterator<number>",
          statements: ["yield 1;", "yield 2;"],
        }
      ]
    }
  ]
});

console.log(sourceFile.print());
```

**Expected behavior**

```typescript
function* foo(): IterableIterator<number> {
    yield 1;
    yield 2;
}
class MyClass {
    * foo(): IterableIterator<number> {
        yield 1;
        yield 2;
    }
}
```

**Actual behavior**
```typescript
function* foo(): IterableIterator<number> {
    yield 1;
    yield 2;
}
class MyClass {
    foo(): IterableIterator<number> {
        yield 1;
        yield 2;
    }
}
```

Note the missing asterisk before the foo() method.

### PR DESCRIPTION
**Pull request by ajvincent**
Fixes #1501 .

### CODE REVIEW

**Comment by ajvincent** [comment]
Huh, I don't see how my change could've broken the build.  But I will note the `Memoize` decorator is not written for the [newer class decorators specification](https://github.com/tc39/proposal-decorators?tab=readme-ov-file#class-methods) which TypeScript 5+ supports.

File: packages/ts-morph/src/tests/structurePrinters/class/methodDeclarationStructurePrinterTests.ts [hunk 1]
```diff
@@ -0,0 +1,105 @@
...
+        isAbstract: true,
+        isAsync: false,
+        isGenerator: false,
+        isStatic: false,
+        name: "method",
+        overloads: [],
+        parameters: [{ name: "p", type: "number" }],
+        returnType: "number",
+        scope: undefined,
+        statements: ["return Promise.resolve(p);"],
```
Comment (ajvincent) [inline packages/ts-morph/src/tests/structurePrinters/class/methodDeclarationStructurePrinterTests.ts:93]: Whoops.  This shouldn't have been in this "isAbstract" test, but it's a good catch point, and it did pass on my build!

**Review by dsherret — APPROVED** [review]
Thanks!
